# SPDX-License-Identifier: Apache-2.0
#
# Crypto material for the ordering organization (one Raft orderer).
OrdererOrgs:
  - Name: Orderer
    Domain: example.com
    EnableNodeOUs: true
    Specs:
      - Hostname: orderer
        SANS:
          - localhost
